name: Build & Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main

  deploy_public:
    name: Deploy Public
    needs:
      - package
    runs-on: [k8s-public]
    container:
      image: registry.gitlab.com/cmmarslender/kubectl-helm:v3.11.2
    steps:
      - uses: actions/checkout@v3

      - name: Vault Login
        uses: Chia-Network/actions/vault/login@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          role_name: github-ecosystem-activity

      - name: Get secrets from vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ env.VAULT_TOKEN }}
          secrets: |
            secret/data/github_users/chiaautomation/ecosystem-activity token | ECOSYSTEM_ACTIVITY_GITHUB_TOKEN;
            secret/data/pub-metrics-eks/rds/rds-info db_host | ECOSYSTEM_ACTIVITY_MYSQL_HOST;
            secret/data/pub-metrics-eks/rds/blocks-write-user username | ECOSYSTEM_ACTIVITY_MYSQL_USER;
            secret/data/pub-metrics-eks/rds/blocks-write-user password | ECOSYSTEM_ACTIVITY_MYSQL_PASSWORD;
            secret/data/fmt/k8s/ghcr_image_pull username | IMAGE_PULL_USERNAME;
            secret/data/fmt/k8s/ghcr_image_pull password | IMAGE_PULL_PASSWORD;

      - name: Get ephemeral aws credentials
        uses: Chia-Network/actions/vault/aws-sts@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          vault_token: ${{ env.VAULT_TOKEN }}
          role_name: pub-metrics-deploy

      - name: Log in to cluster
        run: aws eks update-kubeconfig --name pub-metrics --region us-west-2

      - uses: Chia-Network/actions/k8s/image-pull-secret@main
        with:
          secret_name: ecosystem-activity-image-pull
          namespace: ecosystem-activity
          username: ${{ env.IMAGE_PULL_USERNAME }}
          password: ${{ env.IMAGE_PULL_PASSWORD }}
          docker_server: "ghcr.io"

      - uses: Chia-Network/actions/helm/deploy@main
        env:
          DOCKER_TAG: "sha-${{ github.sha }}"
        with:
          namespace: "ecosystem-activity"
          app_name: "ecosystem-activity"
          helm_chart_repo: "https://chia-network.github.io/helm-charts"
          helm_chart: "generic"
          helm_values: "./k8s/values.yaml"
